# -*- coding: utf-8 -*-
"""run_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rgKeSVKbmyM3o9zL12vYfL0Qa_2YRmdR
"""

# Check GPU
!nvidia-smi

# Basic dependencies
!pip install -q opencv-python pillow tqdm

from google.colab import files
files.upload()   # upload low_res.png or folder

"""**1️⃣ Real-ESRGAN**"""

# Commented out IPython magic to ensure Python compatibility.
# Clone repo
!git clone https://github.com/xinntao/Real-ESRGAN.git
# %cd Real-ESRGAN

# Install dependencies
!pip install -r requirements.txt
!python setup.py develop

# Download pretrained model
!wget https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth -P weights/

!mkdir /content/test_images
!mv /content/animal.jpg /content/old.jpg /content/female.jpg /content/test_images/

!sed -i 's/from torchvision.transforms.functional_tensor import rgb_to_grayscale/from torchvision.transforms.functional import rgb_to_grayscale/' /usr/local/lib/python3.12/dist-packages/basicsr/data/degradations.py

!python inference_realesrgan.py \
  -n RealESRGAN_x4plus \
  -i /content/test_images \
  -o /content/output_realesrgan \
  --outscale 4

"""**2️⃣ GFPGAN (Face Enhancement)**"""

# Commented out IPython magic to ensure Python compatibility.
# Restart runtime before this
!git clone https://github.com/TencentARC/GFPGAN.git
# %cd GFPGAN

!pip install -r requirements.txt
!python setup.py develop

# Download model
!mkdir -p weights
!wget https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.4.pth -P experiments/pretrained_models

!python inference_realesrgan.py \
  -n RealESRGAN_x4plus \
  -i /content/test_images \
  -o /content/output_realesrgan \
  --outscale 4
!python inference_gfpgan.py \
  -i /content/test_images/ \
  -o /content/output_gfpgan \
  -v 1.4 \
  -s 2

"""**3️⃣ CodeFormer (Face Restoration – More Control)**"""

# Commented out IPython magic to ensure Python compatibility.
# Restart runtime
!git clone https://github.com/sczhou/CodeFormer.git
# %cd CodeFormer

!pip install -r requirements.txt
!python basicsr/setup.py develop

# Download weights
!mkdir -p weights
!wget https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth -P weights

!python inference_codeformer.py \
  -i /content/test_images/ \
  -o /content/output_codeformer \
  -w 0.7 \
  --face_upsample

"""**4️⃣ SwinIR (Research-Grade Super-Resolution)**"""

# Commented out IPython magic to ensure Python compatibility.
# Restart runtime
!git clone https://github.com/JingyunLiang/SwinIR.git
# %cd SwinIR

!pip install -r requirements.txt
!mkdir weights
!wget https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/003_realSR_BSRGAN_DFOWMFC_s64w8_SwinIR-L_x4_GAN.pth -P model_zoo

!python main_test_swinir.py \
  --task real_sr \
  --scale 4 \
  --large_model \
  --model_path model_zoo/003_realSR_BSRGAN_DFOWMFC_s64w8_SwinIR-L_x4_GAN.pth \
  --folder_lq /content/test_images \
  --tile 400